{
 "title": "HMI Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "iotalarm ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  metric AS metric,\n  value\nFROM iotalarm\nWHERE\n  $__timeFilter(time)\nORDER BY UNIX_TIMESTAMP(time)"
    }
   ]
  },
  {
   "title": "iotdata",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  metric AS metric,\n  value\nFROM iotdata\nWHERE\n  $__timeFilter(time)\nORDER BY UNIX_TIMESTAMP(time)"
    }
   ]
  },
  {
   "title": "iotcounter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) AS \"time\",\n  metric AS metric,\n  value\nFROM iotcounter\nWHERE\n  $__timeFilter(time)\nORDER BY UNIX_TIMESTAMP(time)"
    }
   ]
  },
  {
   "title": "IotStatus",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n   UNIX_TIMESTAMP(time) AS \"time\",\n  metric AS metric,\n  value\nFROM iotstatus\nWHERE\n  $__timeFilter(time)\nORDER BY UNIX_TIMESTAMP(time)"
    }
   ]
  }
 ]
}